# -*- coding: utf-8 -*-
"""helper_functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15cd38LnbNe-Xb5cbe6KTo1wpu90jQfKE
"""

import tensorflow as tf

import datetime

def create_tensorboard_callback(dir_name, experiment_name):
  """
  It creates a tensorboard callback instand to store log files.

  Store log files with filepath:
    "dir_name/experiment_name/current_datetime/"

  Args:
    dir_name: target directory to store TensorBoard log files
    experiment_name: name of experiment directory
  """
  log_dir = dir_name + "/" + experiment_name + "/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
  tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir)
  print(f"Saving TensorBoard log files into: ", log_dir)
  return tensorboard_callback